import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Covid from './components/Covid'

export default function Home() {
  return (
    <>
      <Head>
        <title>Covid 19 Bilgileri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Covid />
      </main>
    </>
  )
}
